{"name": "Проверка логина при неверном пароле", "status": "passed", "start": 1713606889760, "stop": 1713606890938, "uuid": "eeba1d49-cd44-4b0f-84b3-24602d9ae53c", "historyId": "af887d0d7c186f5d8e52d8da90a51fec", "testCaseId": "af887d0d7c186f5d8e52d8da90a51fec", "fullName": "tests.test_user_login.TestLoginUser#test_login_new_user_with_uncorrect_password_false_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-R1RFFME11IE"}, {"name": "thread", "value": "10192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}