{"name": "Проверка логина при неверном пароле", "status": "passed", "start": 1712519927754, "stop": 1712519928811, "uuid": "dfaf1c78-08b8-4b49-a9a3-ad9cddfaa6df", "historyId": "af887d0d7c186f5d8e52d8da90a51fec", "testCaseId": "af887d0d7c186f5d8e52d8da90a51fec", "fullName": "tests.test_user_login.TestLoginUser#test_login_new_user_with_uncorrect_password_false_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-R1RFFME11IE"}, {"name": "thread", "value": "7708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}