{"name": "Проверка создания уже зарегестрированного пользователя", "status": "passed", "start": 1713606851391, "stop": 1713606852378, "uuid": "51d04f86-1e98-4971-9bd2-7bcba09a04d3", "historyId": "a0c744c8bbb5e28c86edb4b0b3d0cd43", "testCaseId": "a0c744c8bbb5e28c86edb4b0b3d0cd43", "fullName": "tests.test_create_new_user.TestCreateNewUser#test_create_new_user_with_existing_data_error_403", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_new_user"}, {"name": "subSuite", "value": "TestCreateNewUser"}, {"name": "host", "value": "WIN-R1RFFME11IE"}, {"name": "thread", "value": "10192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_new_user"}]}