{"name": "Проверка логина при неверной почте", "status": "passed", "start": 1712519931160, "stop": 1712519932155, "uuid": "4cd2b6d7-28ae-4107-a01d-62abb23101bb", "historyId": "a4a97941f6a1055a6c5c8bbe63f9a0ba", "testCaseId": "a4a97941f6a1055a6c5c8bbe63f9a0ba", "fullName": "tests.test_user_login.TestLoginUser#test_login_new_user_with_uncorrect_email_false_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "WIN-R1RFFME11IE"}, {"name": "thread", "value": "7708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}